language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - hexo g

after_success:
  - cd ./public
  - git init
  - git config user.name "tqlin"
  - git config user.email "smltq@126.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/smltq/blog.git" master:gh-pages

after_script:
  - curl http://49.235.170.100:8787/pull

branches:
  only:
    - master